project:
  type: website
  output-dir: docs

website:
  title: "Quarto Blog"
  site-url: https://oakhi.github.io/Life-Begins-When/
  navbar:
    right:
      - icon: rss
        href: index.xml
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

