---
title: "as you wish"
author: "DK"
date: "2022-11-23"
categories: [love, nostalgia, indirect]
image: "20221019_084239 (1).jpg"
---

At times a popular movie alters and captures the mindset and imagination of a whole generation -- and beyond.  

One such movie, for my generation, was the **Princess Bride**, released in 1987.

The movie fulfilled a need of that time period by re-visiting tried and true movie making approaches -- with a modern twist.

Action-Romantic-Comedy, not necessarily in the order of importance, would be one classification of the movie.  But like all great movies, it created its own genre and became a source of Vulgate for years to come.

Beyond its romance tinged plot, the witty dialogue won me over.

<https://www.businessinsider.com/best-quotes-from-the-princess-bride-list-2017-9>

\

**Grandpa**: Nothing gave **Buttercup** as much pleasure as ordering **Westley** around.

**Buttercup**: Farm boy, polish my horse's saddle. I want to see my face shining in it by morning.

**Westley**: As you wish.

**Grandpa**: "As you wish" was all he ever said to her.

**Buttercup**: Farm boy, fill these with water - please.

**Westley**: As you wish.

**Grandpa**: That day, she was amazed to discover that when he was saying "**As you wish**," what he

meant was, "**I love you**." And even more amazing was the day she realized she truly loved him back.

**Buttercup**: Farm boy \... fetch me that pitcher.

**Westley**: As you wish.

\

When a relationship is solid, growing, and nurturing, voices are subdued.

At times no sound is needed.

For \"As you wish\" can be conveyed, just as well, without words

The Lord God speaks in a still, small voice.

When people are listening, following, obeying, no dramatic intervention is needed.

If not, 災難 (disasters), wars and rumors of war and captivity of nations and souls follow.

**Princess Bride** showed that the dialogues are just as important, perhaps more important than actions in movies -- as the popularity of Korean Dramas have recently demonstrated.
