---
title: "Dreams to Fulfill"
author: "DK"
date: "2023-02-29"
categories: [family, recollections]
draft: true
image: "20230108_171658-01 (1).jpeg"
---

If my mom had a dream role for me, it would be an accordion playing, western medicine doctor.

Why a western medicine doctor?

Her family has either an oriental or western medicine doctor in each generation, going back a number of generations.

She thought one of us would make a good doctor.

That assignment was fulfilled by my cousin from Seoul.

It might be also that her father passed away waiting for a doctor to arrive, who happens to be related to him.
He knew his time to die was near and he hung a pocket watch and predicted,

> "...if he doesn't arrive by this hour, my life is over"

He did wait and the doctor relative arrived too late to save him.

## The Accordion

Not sure if mom played accordion growing up or knew someone that played the instrument.
But she was very partial to that instrument.

Koreans as nation love that instrument.

Expert players are accorded a legendary status.

Many of the Trot singers utilize the guitar and accordions.

One reason maybe the instrument captures the mood, especially the sorrowful, unfulfilled past of the people

## The Effect of the War

Education
Marriage
Survival



